Kindergarten school/Kindergarten school/Controllers/DailyreportsController.cs
using Kindergarten_school.Hubs;
using Kindergarten_school.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using Microsoft.EntityFrameworkCore;
using MongoDB.Driver;

namespace Kindergarten_school.Controllers
{
    public class DailyreportsController : Controller
    {
        private readonly IMongoCollection<Parent> _parentCollection;
        private readonly IMongoCollection<StudentModel> _studentCollection;
        private readonly IMongoCollection<ClassModel> _classCollection;
        private readonly IMongoCollection<DailyreportsModel> _dailyreports;
        private readonly IHubContext<ReportsHub> _hubContext;


        public DailyreportsController(IMongoDatabase database, IHubContext<ReportsHub> hubContext)
        {
            _parentCollection = database.GetCollection<Parent>("parents");
            _studentCollection = database.GetCollection<StudentModel>("students");
            _dailyreports = database.GetCollection<DailyreportsModel>("dailyreports");
            _classCollection = database.GetCollection<ClassModel>("classes");

            _hubContext = hubContext;

        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            ViewBag.ListClass = await _classCollection.Find(_ => true).ToListAsync();
            ViewBag.ListStudent = await _studentCollection.Find(_ => true).ToListAsync();
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(DailyreportsModel model)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.ListClass = await _classCollection.Find(_ => true).ToListAsync();
                ViewBag.ListStudent = await _studentCollection.Find(_ => true).ToListAsync();

                return View(model);
            }

            var lastReport = await _dailyreports.Find(_ => true)
                .SortByDescending(r => r.ReportID)
                .Limit(1)
                .FirstOrDefaultAsync();

            model.ReportID = (lastReport != null) ? lastReport.ReportID + 1 : 1;
            model.ReportDate = DateTime.Now;
            await _dailyreports.InsertOneAsync(model);
            await _hubContext.Clients.All.SendAsync("ReceiveMessageUser", model.ReportDate, model.Activities, model.Meal, model.NapTime, model.Description);
            return RedirectToAction("Index");
        }
    }
}

Kindergarten school/Kindergarten school/Views/Dailyreports/Index.cshtml
@model Kindergarten_school.Models.DailyreportsModel
@{
    List<Kindergarten_school.Models.ClassModel> listClass = ViewBag.ListClass;
    List<Kindergarten_school.Models.StudentModel> listStudent = ViewBag.ListStudent;
}

<h2>Tiến độ học tập giáo viên</h2>

<form asp-action="Index" asp-controller="Dailyreports" method="post">
    <div class="form-group">
        <label for="Activities">Hoạt động</label>
        <input type="text" class="form-control" id="Activities" name="Activities" required />
    </div>
    <div class="form-group">
        <label for="Meal">Ăn uống</label>
        <input type="text" class="form-control" id="Meal" name="Meal" required />
    </div>
    <div class="form-group">
        <label for="NapTime">Hiện tại</label>
        <input type="text" class="form-control" id="NapTime" name="NapTime" />
    </div>
    <div class="form-group">
        <label for="Description">Mô tả</label>
        <input type="text" class="form-control" id="Description" name="Description" required />
    </div>
    <div class="form-group">
        <label for="ClassID">Lớp học</label>
        <select id="ClassID" name="ClassID" class="form-control">
            @foreach (var item in listClass)
            {
                <option value="@item.ClassID">@item.ClassName</option>
            }
        </select>
    </div>
    <div class="form-group">
        <label for="StudentID">Học sinh</label>
        <select id="StudentID" name="StudentID" class="form-control">
            @foreach (var item in listStudent)
            {
                <option value="@item.StudentID">@item.FirstName @item.LastName</option>
            }
        </select>
    </div>
    <button type="submit" class="btn btn-success mt-3">Lưu</button>
</form>

@if (!ViewData.ModelState.IsValid)
{
    <div class="alert alert-danger mt-3">
        Vui lòng kiểm tra lại thông tin!
    </div>
}